/**
 * Human-Readable Generator
 *
 * Reads state.json → generates TASK.md + CHANGELOG.md in human/ directory
 * These files are READ-ONLY for humans. Agents write to protocol/ only.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join } from 'path'
import type { MACSState, TaskState, GlobalEvent } from './schema.js'

function readJson<T>(filePath: string): T | null {
  if (!existsSync(filePath)) return null
  return JSON.parse(readFileSync(filePath, 'utf-8'))
}

function readJsonl<T>(filePath: string): T[] {
  if (!existsSync(filePath)) return []
  const content = readFileSync(filePath, 'utf-8').trim()
  if (!content) return []
  return content.split('\n').map(line => JSON.parse(line))
}

export class HumanGenerator {
  private dir: string
  private protocolDir: string
  private humanDir: string

  constructor(projectRoot: string) {
    this.dir = join(projectRoot, '.macs')
    this.protocolDir = join(this.dir, 'protocol')
    this.humanDir = join(this.dir, 'human')
  }

  generate(): void {
    mkdirSync(this.humanDir, { recursive: true })
    this.generateTaskMd()
    this.generateChangelogMd()
    this.generateStatusMd()
  }

  // ----------------------------------------------------------
  // TASK.md
  // ----------------------------------------------------------

  private generateTaskMd(): void {
    const state = readJson<MACSState>(join(this.protocolDir, 'state.json'))
    if (!state) return

    const tasks = Object.values(state.tasks)
    const lines: string[] = [
      '# TASK',
      '',
      `> Auto-generated from \`.macs/protocol/state.json\` at ${new Date().toISOString()}`,
      '> **Do not edit this file.** Agents write to `.macs/protocol/tasks.jsonl`.',
      '',
    ]

    // Group by status
    const groups: Record<string, TaskState[]> = {
      in_progress: [],
      blocked: [],
      assigned: [],
      pending: [],
      completed: [],
      cancelled: [],
    }

    for (const task of tasks) {
      if (groups[task.status]) {
        groups[task.status].push(task)
      }
    }

    const statusEmoji: Record<string, string> = {
      in_progress: '🔄',
      blocked: '🚫',
      assigned: '📋',
      pending: '⏳',
      completed: '✅',
      cancelled: '❌',
    }

    const statusLabel: Record<string, string> = {
      in_progress: 'In Progress',
      blocked: 'Blocked',
      assigned: 'Assigned',
      pending: 'Pending',
      completed: 'Completed',
      cancelled: 'Cancelled',
    }

    // Summary
    const m = state.metrics
    lines.push(`## Summary`)
    lines.push('')
    lines.push(`| Total | In Progress | Blocked | Pending | Completed |`)
    lines.push(`|-------|-------------|---------|---------|-----------|`)
    lines.push(`| ${m.total_tasks} | ${m.in_progress} | ${m.blocked} | ${m.pending} | ${m.completed} |`)
    lines.push('')

    // Each group
    for (const status of ['in_progress', 'blocked', 'assigned', 'pending', 'completed', 'cancelled']) {
      const group = groups[status]
      if (group.length === 0) continue

      lines.push(`## ${statusEmoji[status]} ${statusLabel[status]} (${group.length})`)
      lines.push('')

      for (const task of group) {
        const checkbox = task.status === 'completed' ? '[x]' : '[ ]'
        lines.push(`### ${checkbox} ${task.id} ${task.title}`)
        lines.push(`- **priority**: ${task.priority}`)
        if (task.assignee) lines.push(`- **owner**: ${task.assignee}`)
        if (task.depends.length > 0) lines.push(`- **depends**: ${task.depends.join(', ')}`)
        if (task.affects.length > 0) lines.push(`- **affects**: ${task.affects.join(', ')}`)
        if (task.tags.length > 0) lines.push(`- **tags**: ${task.tags.join(', ')}`)
        if (task.started_at) lines.push(`- **started**: ${task.started_at}`)
        if (task.completed_at) lines.push(`- **completed**: ${task.completed_at}`)
        if (task.artifacts.length > 0) lines.push(`- **artifacts**: ${task.artifacts.join(', ')}`)
        if (task.summary) lines.push(`- **summary**: ${task.summary}`)

        // Blocked history
        if (task.blocked_history.length > 0) {
          const lastBlock = task.blocked_history[task.blocked_history.length - 1]
          if (!lastBlock.unblocked_at) {
            lines.push(`- **blocked_reason**: ${lastBlock.reason}`)
          }
        }

        lines.push('')
      }
    }

    writeFileSync(join(this.humanDir, 'TASK.md'), lines.join('\n'), 'utf-8')
  }

  // ----------------------------------------------------------
  // CHANGELOG.md
  // ----------------------------------------------------------

  private generateChangelogMd(): void {
    const events = readJsonl<GlobalEvent>(join(this.protocolDir, 'events.jsonl'))
    if (events.length === 0) return

    const lines: string[] = [
      '# CHANGELOG',
      '',
      `> Auto-generated from \`.macs/protocol/events.jsonl\` at ${new Date().toISOString()}`,
      '> **Do not edit this file.** Agents write to `.macs/protocol/events.jsonl`.',
      '',
    ]

    // Group events by date
    const byDate = new Map<string, GlobalEvent[]>()
    for (const event of events) {
      const date = event.ts.split('T')[0]
      if (!byDate.has(date)) byDate.set(date, [])
      byDate.get(date)!.push(event)
    }

    // Sort dates descending
    const dates = Array.from(byDate.keys()).sort().reverse()

    for (const date of dates) {
      lines.push(`## [${date}]`)
      lines.push('')

      const dayEvents = byDate.get(date)!

      for (const event of dayEvents) {
        const time = event.ts.split('T')[1]?.slice(0, 8) || ''
        const taskRef = event.task ? ` (${event.task})` : ''

        switch (event.type) {
          case 'file_modified':
            lines.push(`- **[Modified]** \`${event.data.path}\` ${event.data.diff_summary} — by ${event.by}${taskRef}`)
            if (event.data.purpose) lines.push(`  - ${event.data.purpose}`)
            break

          case 'decision_made':
            lines.push(`- **[Decision]** ${event.data.question} → **${event.data.decision}** — by ${event.by}${taskRef}`)
            if (event.data.rationale) lines.push(`  - Rationale: ${event.data.rationale}`)
            break

          case 'conflict_detected':
            lines.push(`- **[Conflict]** \`${event.data.file}\` — between ${event.data.agents.join(', ')}`)
            break

          case 'conflict_resolved':
            lines.push(`- **[Resolved]** \`${event.data.file}\` — strategy: ${event.data.strategy}${event.data.winner ? `, winner: ${event.data.winner}` : ''}`)
            break

          case 'test_passed':
            lines.push(`- **[Test ✅]** ${event.data.suite}: ${event.data.passed}/${event.data.tests} passed (${event.data.duration_ms}ms) — by ${event.by}${taskRef}`)
            break

          case 'test_failed':
            lines.push(`- **[Test ❌]** ${event.data.suite}: ${event.data.failed} failed — by ${event.by}${taskRef}`)
            for (const err of event.data.errors.slice(0, 3)) {
              lines.push(`  - ${err}`)
            }
            break

          case 'breaking_change':
            lines.push(`- **[⚠️ Breaking]** \`${event.data.file}\`: ${event.data.description} — by ${event.by}${taskRef}`)
            if (event.data.migration) lines.push(`  - Migration: ${event.data.migration}`)
            lines.push(`  - Affected: ${event.data.affected_agents.join(', ')}`)
            break

          case 'agent_registered':
            lines.push(`- **[Agent]** ${event.data.agent_id} registered (${event.data.capabilities.join(', ')})`)
            break

          default:
            // Skip heartbeats, locks etc in changelog
            break
        }
      }

      lines.push('')
    }

    writeFileSync(join(this.humanDir, 'CHANGELOG.md'), lines.join('\n'), 'utf-8')
  }

  // ----------------------------------------------------------
  // STATUS.md — quick overview
  // ----------------------------------------------------------

  private generateStatusMd(): void {
    const state = readJson<MACSState>(join(this.protocolDir, 'state.json'))
    if (!state) return

    const lines: string[] = [
      '# Project Status',
      '',
      `> Updated: ${state.updated_at}`,
      '',
    ]

    // Agents
    const agents = Object.values(state.agents)
    if (agents.length > 0) {
      lines.push('## Agents')
      lines.push('')
      lines.push('| Agent | Status | Current Task | Completed | Avg Time |')
      lines.push('|-------|--------|-------------|-----------|----------|')
      for (const agent of agents) {
        const avgMin = agent.stats.avg_task_time_ms
          ? `${Math.round(agent.stats.avg_task_time_ms / 60000)}min`
          : '-'
        lines.push(`| ${agent.id} | ${agent.status} | ${agent.current_task || '-'} | ${agent.stats.tasks_completed} | ${avgMin} |`)
      }
      lines.push('')
    }

    // Locks
    if (state.locks.length > 0) {
      lines.push('## Active Locks')
      lines.push('')
      for (const lock of state.locks) {
        lines.push(`- \`${lock.file}\` locked by ${lock.locked_by} (${lock.reason || 'no reason'})`)
      }
      lines.push('')
    }

    // Metrics
    const m = state.metrics
    lines.push('## Metrics')
    lines.push('')
    lines.push(`- Tasks: ${m.completed}/${m.total_tasks} completed`)
    lines.push(`- In progress: ${m.in_progress}`)
    lines.push(`- Blocked: ${m.blocked}`)
    lines.push(`- Active agents: ${m.active_agents}`)
    lines.push(`- Conflicts: ${m.conflict_count}`)
    lines.push(`- Breaking changes: ${m.breaking_changes}`)
    lines.push('')

    writeFileSync(join(this.humanDir, 'STATUS.md'), lines.join('\n'), 'utf-8')
  }
}
